name: Markdown
on:
  push:
    branches:
      - master
    paths:
      - readme.md
      - .github/workflows/markdown.yml
jobs:
  markdown:
    if: github.repository == 'qdm12/youtube-dl-docker'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: peter-evans/dockerhub-description@v3
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/youtube-dl-alpine
          short-description: Youtube-dl in an Alpine container
          readme-filepath: readme.md
